[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "openai>=1.109.1",
    "pandas>=2.3.2",
    "requests>=2.32.5",
    "streamlit>=1.50.0",
]
